version: '2'
services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '55025:1025'
      - '55080:1080'

  postgres-development:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - '55432:5432'
    volumes:
      - postgres-development-data:/var/lib/postgresql/data:cached

  postgres-test:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data:cached

  app:
    tty: true
    stdin_open: true
    environment:
      DISABLE_SPRING: 1
      BUNDLE_JOBS: 4
      BUNDLE_PATH: /usr/src/app/vendor/bundle
      BUNDLE_GEMFILE: /usr/src/app/Gemfile
      SMTP_ADDRESS: mailcatcher
      SMTP_PORT: 1025
      MAILER_DELIVERY_METHOD: smtp
      DATABASE_HOST: postgres-development
      TEST_DATABASE_HOST: postgres-test
      HISTFILE: /usr/src/app/log/sh_history.log
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - '55000:3000'
    volumes:
      - .:/usr/src/app:cached
      - bundle-data:/usr/src/app/vendor/bundle:cached
      - tmp-data:/usr/src/app/tmp:cached
      - packs-data:/usr/src/app/public/packs:cached
      - packs-test-data:/usr/src/app/public/packs-test:cached
      - node_modules-data:/usr/src/app/node_modules:cached
      - log-data:/usr/src/app/log:cached
      # exclude volumes
      - /usr/src/app/.git
    dns:
      - 8.8.8.8
      - 8.8.8.4
    links:
      - mailcatcher
      - postgres-test
      - postgres-development

volumes:
  postgres-development-data:
    driver: local
  postgres-test-data:
    driver: local
  bundle-data:
    driver: local
  tmp-data:
    driver: local
  node_modules-data:
    driver: local
  log-data:
    driver: local
  packs-data:
    driver: local
  packs-test-data:
    driver: local

